### PR TITLE
Amendment to Legitimize Online Voting

### PR DESCRIPTION
**Pull request by hannogrimm**
I propose an amendment to §10 of the Rules of Procedure of the General Student Assembly regarding the eligibility of voting through the _physical_ presence of the quorum. 

This paragraph has been passed in a time where the count of members of the student body of CODE was relatively low compared to the count of students we understand as members of the student body today. Physical presence of the majority of students was possible back then. 

Today, with regards to our need for remote participation due to the circumstances of the Covid-19 pandemic, and the resulting inability to gather a representing group of students on campus to hold our Student General Assemblies in physical presence, the ability to establish a quorum represented by 10% of the student body membership ([§10 p.1 ROP](https://github.com/codeuniversity/student-council/blob/main/rules-of-procedure/rules-of-procedure.md#prerequisites-for-a-quorum-attendance-list)) in physical presence has become very difficult. 

The ability to vote via online mechanisms is also a favorable step for the long-term development of the student body as we will inevitably grow a larger community of individuals living and working from different places around the globe. This amendment ensures that their right for participation is included.

These changes _allow_ the use of online votings. It is written in a manner that does not inherently favor them but legitimizes their use. I am hopeful that we will facilitate physical General Assemblies when possible as I am confident that they will lead to more active participation. 

I am happy to see suggestions and comments to my requested changes!

### CODE REVIEW

**Comment by BMG93** [comment]
This seems like a common sense change and one that definitely makes our processes more democratic and inclusive while we remain remote first.

**Comment by hannogrimm** [comment]
A voting to these changes has been scheduled in the next Student General Assembly on Friday, 3rd September 2021 5:30pm. The voting will be held in person (for obvious reasons).

**Comment by hannogrimm** [comment]
Passed on September 3rd by majority vote in person.

**Review by FabianVolkers — DISMISSED** [review]
Looks good to me

**Review by FabianVolkers — APPROVED** [review]

**Pull request merged**
